# Generated by Django 5.2 on 2025-06-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0007_bikeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.bikesdetails'),
            preserve_default=False,
        ),
    ]
