# Generated by Django 5.2 on 2025-06-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_bike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='time',
        ),
    ]
