# Generated by Django 5.2 on 2025-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinfo',
            name='MoreImage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productsinfo',
            name='fullDescription',
            field=models.TextField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='productsinfo',
            name='technicalDescription',
            field=models.TextField(blank=True, max_length=455, null=True),
        ),
    ]
