# Generated by Django 5.2 on 2025-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsinfo_moreimage_productsinfo_fulldescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfo',
            name='MoreImage',
        ),
        migrations.RemoveField(
            model_name='productsinfo',
            name='fullDescription',
        ),
        migrations.RemoveField(
            model_name='productsinfo',
            name='technicalDescription',
        ),
    ]
