# Generated by Django 5.2 on 2025-05-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_bikesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
