# Generated by Django 5.0 on 2025-06-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_batterie'),
    ]

    operations = [
        migrations.CreateModel(
            name='batterie_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='batterie')),
                ('batterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.batterie')),
            ],
        ),
    ]
