# Generated by Django 5.0 on 2025-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_batterie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesdetails',
            name='name',
            field=models.CharField(default=1, max_length=455),
            preserve_default=False,
        ),
    ]
