# Generated by Django 5.0 on 2025-06-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bikesdetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='trotinette_electrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trotinette')),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=455)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='trotinette_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trotinette')),
                ('trotinette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.batterie')),
            ],
        ),
    ]
