# Generated by Django 5.2 on 2025-06-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_trotinette_electrique_trotinette_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trotinette_image',
            name='trotinette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.trotinette_electrique'),
        ),
    ]
