# Generated by Django 5.2 on 2025-08-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_trotinette_image_trotinette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfo',
            name='price',
        ),
    ]
