# Generated by Django 5.0 on 2025-08-28 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productsinfo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikesdetails',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='bikesdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bikesdetails',
            name='technicalDescription',
        ),
        migrations.AddField(
            model_name='bikesdetails',
            name='annee',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikesdetails',
            name='couleur',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikesdetails',
            name='kilometrage',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikesdetails',
            name='puissance',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
